#!/bin/sh
cd "${0%/*}" || exit 1

. "${WM_PROJECT_DIR:?source an OpenFOAM environment first}"/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh

# ************************************************************************* //
